create static categories drink page
GSG-CF04/TOP-CHEF pull request #55
Opened 2021-12-02 10:20 UTC by MohammedDahalan

Relates #25

2021-12-02 10:49 UTC, IsraaHamdi requested changes
edit style for tablet and desktop screen

2021-12-02 11:03 UTC, muhannaAtalla20 approved these changes

2021-12-02 11:52 UTC, yaqootturman requested changes
change the files name for camelCase convention

2021-12-02 11:52 UTC, yaqootturman commented on otherPages/categories/categoriesDrink.html
> +        <div class="category" style="background-image: url(../../assets/images/cateories/drink/Ordinary\ Drink.jpg)">
you shouldn't add style here

2021-12-02 11:52 UTC, yaqootturman commented on otherPages/categories/categoriesDrink.html
> +    <section class="carousel" data-flickity='{ "groupCells": true }'>
No need for slides if its not work correctly

2021-12-02 11:52 UTC, yaqootturman commented on otherPages/categories/categoriesDrink.html
> +      <img class="logo" src="../../assets/images/logo.png" alt="" />
add alt

2021-12-02 11:52 UTC, yaqootturman commented on otherPages/categories/categoriesDrink.html
> +    <title>TOP CHEF</title>
this title is for this page not for the app

2021-12-02 12:31 UTC, IsraaHamdi commented on otherPages/categories/categoriesDrink.html
> +        <div class="category" style="background-image: url(../../assets/images/cateories/drink/Ordinary\ Drink.jpg)">
using inline style there because this image fetch from api  when create the element using dom

2021-12-03 19:48 UTC, IsraaHamdi approved these changes

2021-12-03 19:58 UTC, farahalzard approved these changes

2021-12-04 06:47 UTC, yaqootturman requested changes
change files name

2021-12-04 10:33 UTC, IsraaHamdi commented
> change files name

what the files needed to change name

2021-12-04 11:34 UTC, IsraaHamdi commented
> > change files name
> 
> what the files needed to change

2021-12-05 11:49 UTC, yaqootturman approved these changes

2021-12-05 11:54 UTC, merged