Write JS for Search in Page Type Food
GSG-CF04/TOP-CHEF pull request #56
Opened 2021-12-03 07:43 UTC by muhannaAtalla20

Relates #43

2021-12-03 07:58 UTC, IsraaHamdi requested changes
edit the title and when click the categories in categoriesFood page that all return just Beef  so edit this also

2021-12-03 21:52 UTC, muhannaAtalla20 commented
> edit the title and when click the categories in categoriesFood page that all return just Beef so edit this also

This one has a issues of its own

2021-12-04 07:10 UTC, yaqootturman requested changes

2021-12-04 07:10 UTC, yaqootturman commented on js/typeFood.js
> +    console.log(e.key)
delete

2021-12-04 07:10 UTC, yaqootturman commented on js/typeFood.js
> +    // console.log(final);
delete

2021-12-04 07:55 UTC, muhannaAtalla20 commented on js/typeFood.js
> +    console.log(e.key)
done

2021-12-04 07:56 UTC, muhannaAtalla20 commented on js/typeFood.js
> +    // console.log(final);
done

2021-12-04 08:42 UTC, yaqootturman approved these changes

2021-12-04 10:29 UTC, IsraaHamdi approved these changes

2021-12-04 11:27 UTC, farahalzard approved these changes

2021-12-04 14:30 UTC, merged